version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform"
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.9.0/terraform_1.9.0_linux_amd64.zip
      - unzip terraform.zip -d /usr/local/bin

  pre_build:
    commands:
      - cd "$CODEBUILD_SRC_DIR/workload" && terraform init -input=false

  build:
    commands:
      - echo "Copying reviewed plan into place"
      - cp "$CODEBUILD_SRC_DIR_scan_output/workload/tfplan.binary" "$CODEBUILD_SRC_DIR/workload/tfplan.binary"
      - echo "Applying the reviewed plan"
      - cd "$CODEBUILD_SRC_DIR/workload" && terraform apply -input=false tfplan.binary
